# Generated by Django 3.0.6 on 2020-05-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelec', '0002_auto_20200530_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
